### ISSUE TITLE
Scan function not working on Android 11

### ISSUE THREAD

**Issue by binu8051** [prasad-psp/Android-Bluetooth-Library#2]

**Comment by prasad-psp** [comment]
**Did you granted location permission to the application?**
Location permission should be enable for the application to scan Bluetooth devices.

**Comment by binu8051** [comment]
yes, i did.

**Comment by prasad-psp** [comment]
Please share your location permission code and Bluetooth scan function code?

**Comment by prasad-psp** [comment]
Please try this solutions:

1. If you have already not checked whether the location permission is enabled or not in the app settings ( go to app info >> Permissions >> Location) then check it.

2. Reset Bluetooth settings

3. Turn off on Bluetooth

4. Restart your Device

5. Turn on off flight mode
